#!/bin/bash

# 设置根目录名称
ROOT_DIR="00_foundations"

# 创建根目录
mkdir -p "$ROOT_DIR"
touch "$ROOT_DIR/README.md"

# 01_llm_architectures
mkdir -p "$ROOT_DIR/01_llm_architectures/transformer_fundamentals"
touch "$ROOT_DIR/01_llm_architectures/transformer_fundamentals/attention_mechanism.md"
touch "$ROOT_DIR/01_llm_architectures/transformer_fundamentals/multi_head_attention.md"
touch "$ROOT_DIR/01_llm_architectures/transformer_fundamentals/positional_encoding.md"
touch "$ROOT_DIR/01_llm_architectures/transformer_fundamentals/layer_normalization.md"
touch "$ROOT_DIR/01_llm_architectures/transformer_fundamentals/feed_forward_networks.md"

mkdir -p "$ROOT_DIR/01_llm_architectures/transformer_variants"
touch "$ROOT_DIR/01_llm_architectures/transformer_variants/gpt_architecture.md"
touch "$ROOT_DIR/01_llm_architectures/transformer_variants/llama_innovations.md"
touch "$ROOT_DIR/01_llm_architectures/transformer_variants/palm_pathways.md"
touch "$ROOT_DIR/01_llm_architectures/transformer_variants/t5_encoder_decoder.md"
touch "$ROOT_DIR/01_llm_architectures/transformer_variants/bert_bidirectional.md"
touch "$ROOT_DIR/01_llm_architectures/transformer_variants/moe_architectures.md"

mkdir -p "$ROOT_DIR/01_llm_architectures/scaling_laws"
touch "$ROOT_DIR/01_llm_architectures/scaling_laws/chinchilla_scaling.md"
touch "$ROOT_DIR/01_llm_architectures/scaling_laws/compute_optimal_training.md"
touch "$ROOT_DIR/01_llm_architectures/scaling_laws/parameter_vs_data.md"
touch "$ROOT_DIR/01_llm_architectures/scaling_laws/emergent_abilities.md"
touch "$ROOT_DIR/01_llm_architectures/scaling_laws/scaling_predictions.md"

mkdir -p "$ROOT_DIR/01_llm_architectures/attention_optimizations"
touch "$ROOT_DIR/01_llm_architectures/attention_optimizations/flash_attention.md"
touch "$ROOT_DIR/01_llm_architectures/attention_optimizations/linear_attention.md"
touch "$ROOT_DIR/01_llm_architectures/attention_optimizations/sparse_attention.md"
touch "$ROOT_DIR/01_llm_architectures/attention_optimizations/sliding_window.md"
touch "$ROOT_DIR/01_llm_architectures/attention_optimizations/rope_alibi.md"

mkdir -p "$ROOT_DIR/01_llm_architectures/model_analysis"
touch "$ROOT_DIR/01_llm_architectures/model_analysis/parameter_counting.md"
touch "$ROOT_DIR/01_llm_architectures/model_analysis/flops_analysis.md"
touch "$ROOT_DIR/01_llm_architectures/model_analysis/memory_requirements.md"
touch "$ROOT_DIR/01_llm_architectures/model_analysis/inference_complexity.md"
touch "$ROOT_DIR/01_llm_architectures/model_analysis/bottleneck_analysis.md"

# 02_training_paradigms
mkdir -p "$ROOT_DIR/02_training_paradigms/pretraining"
touch "$ROOT_DIR/02_training_paradigms/pretraining/language_modeling.md"
touch "$ROOT_DIR/02_training_paradigms/pretraining/causal_lm.md"
touch "$ROOT_DIR/02_training_paradigms/pretraining/masked_lm.md"
touch "$ROOT_DIR/02_training_paradigms/pretraining/prefix_lm.md"
touch "$ROOT_DIR/02_training_paradigms/pretraining/data_preparation.md"
touch "$ROOT_DIR/02_training_paradigms/pretraining/tokenization.md"
touch "$ROOT_DIR/02_training_paradigms/pretraining/curriculum_learning.md"

mkdir -p "$ROOT_DIR/02_training_paradigms/fine_tuning"
touch "$ROOT_DIR/02_training_paradigms/fine_tuning/supervised_fine_tuning.md"
touch "$ROOT_DIR/02_training_paradigms/fine_tuning/instruction_tuning.md"
touch "$ROOT_DIR/02_training_paradigms/fine_tuning/task_specific_tuning.md"
touch "$ROOT_DIR/02_training_paradigms/fine_tuning/few_shot_learning.md"
touch "$ROOT_DIR/02_training_paradigms/fine_tuning/in_context_learning.md"
touch "$ROOT_DIR/02_training_paradigms/fine_tuning/prompt_engineering.md"

mkdir -p "$ROOT_DIR/02_training_paradigms/parameter_efficient"
touch "$ROOT_DIR/02_training_paradigms/parameter_efficient/lora_analysis.md"
touch "$ROOT_DIR/02_training_paradigms/parameter_efficient/qlora_quantization.md"
touch "$ROOT_DIR/02_training_paradigms/parameter_efficient/dora_improvements.md"
touch "$ROOT_DIR/02_training_paradigms/parameter_efficient/adapter_methods.md"
touch "$ROOT_DIR/02_training_paradigms/parameter_efficient/prefix_tuning.md"
touch "$ROOT_DIR/02_training_paradigms/parameter_efficient/prompt_tuning.md"
touch "$ROOT_DIR/02_training_paradigms/parameter_efficient/peft_comparison.md"

mkdir -p "$ROOT_DIR/02_training_paradigms/continual_learning"
touch "$ROOT_DIR/02_training_paradigms/continual_learning/catastrophic_forgetting.md"
touch "$ROOT_DIR/02_training_paradigms/continual_learning/elastic_weight_consolidation.md"
touch "$ROOT_DIR/02_training_paradigms/continual_learning/progressive_networks.md"
touch "$ROOT_DIR/02_training_paradigms/continual_learning/memory_replay.md"
touch "$ROOT_DIR/02_training_paradigms/continual_learning/meta_learning.md"

mkdir -p "$ROOT_DIR/02_training_paradigms/evaluation_metrics"
touch "$ROOT_DIR/02_training_paradigms/evaluation_metrics/perplexity.md"
touch "$ROOT_DIR/02_training_paradigms/evaluation_metrics/bleu_rouge.md"
touch "$ROOT_DIR/02_training_paradigms/evaluation_metrics/bertscore.md"
touch "$ROOT_DIR/02_training_paradigms/evaluation_metrics/human_evaluation.md"
touch "$ROOT_DIR/02_training_paradigms/evaluation_metrics/benchmark_suites.md"

# 03_distributed_systems
mkdir -p "$ROOT_DIR/03_distributed_systems/parallel_computing"
touch "$ROOT_DIR/03_distributed_systems/parallel_computing/parallel_paradigms.md"
touch "$ROOT_DIR/03_distributed_systems/parallel_computing/shared_memory.md"
touch "$ROOT_DIR/03_distributed_systems/parallel_computing/distributed_memory.md"
touch "$ROOT_DIR/03_distributed_systems/parallel_computing/message_passing.md"
touch "$ROOT_DIR/03_distributed_systems/parallel_computing/data_parallelism.md"
touch "$ROOT_DIR/03_distributed_systems/parallel_computing/model_parallelism.md"
touch "$ROOT_DIR/03_distributed_systems/parallel_computing/pipeline_parallelism.md"

mkdir -p "$ROOT_DIR/03_distributed_systems/communication_primitives"
touch "$ROOT_DIR/03_distributed_systems/communication_primitives/point_to_point.md"
touch "$ROOT_DIR/03_distributed_systems/communication_primitives/collective_operations.md"
touch "$ROOT_DIR/03_distributed_systems/communication_primitives/allreduce_allgather.md"
touch "$ROOT_DIR/03_distributed_systems/communication_primitives/broadcast_scatter.md"
touch "$ROOT_DIR/03_distributed_systems/communication_primitives/reduce_scatter.md"
touch "$ROOT_DIR/03_distributed_systems/communication_primitives/nccl_primitives.md"
touch "$ROOT_DIR/03_distributed_systems/communication_primitives/communication_patterns.md"

mkdir -p "$ROOT_DIR/03_distributed_systems/consistency_models"
touch "$ROOT_DIR/03_distributed_systems/consistency_models/strong_consistency.md"
touch "$ROOT_DIR/03_distributed_systems/consistency_models/eventual_consistency.md"
touch "$ROOT_DIR/03_distributed_systems/consistency_models/causal_consistency.md"
touch "$ROOT_DIR/03_distributed_systems/consistency_models/synchronous_training.md"
touch "$ROOT_DIR/03_distributed_systems/consistency_models/asynchronous_training.md"
touch "$ROOT_DIR/03_distributed_systems/consistency_models/federated_learning.md"

mkdir -p "$ROOT_DIR/03_distributed_systems/fault_tolerance"
touch "$ROOT_DIR/03_distributed_systems/fault_tolerance/failure_models.md"
touch "$ROOT_DIR/03_distributed_systems/fault_tolerance/checkpointing.md"
touch "$ROOT_DIR/03_distributed_systems/fault_tolerance/replication.md"
touch "$ROOT_DIR/03_distributed_systems/fault_tolerance/recovery_strategies.md"
touch "$ROOT_DIR/03_distributed_systems/fault_tolerance/elastic_training.md"

mkdir -p "$ROOT_DIR/03_distributed_systems/scalability_theory"
touch "$ROOT_DIR/03_distributed_systems/scalability_theory/amdahls_law.md"
touch "$ROOT_DIR/03_distributed_systems/scalability_theory/gustafsons_law.md"
touch "$ROOT_DIR/03_distributed_systems/scalability_theory/strong_weak_scaling.md"
touch "$ROOT_DIR/03_distributed_systems/scalability_theory/communication_cost.md"
touch "$ROOT_DIR/03_distributed_systems/scalability_theory/load_balancing.md"

# 04_rlhf_fundamentals
mkdir -p "$ROOT_DIR/04_rlhf_fundamentals/reinforcement_learning"
touch "$ROOT_DIR/04_rlhf_fundamentals/reinforcement_learning/mdp_framework.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/reinforcement_learning/value_functions.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/reinforcement_learning/policy_methods.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/reinforcement_learning/actor_critic.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/reinforcement_learning/policy_gradient.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/reinforcement_learning/ppo_algorithm.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/reinforcement_learning/exploration_exploitation.md"

mkdir -p "$ROOT_DIR/04_rlhf_fundamentals/human_feedback"
touch "$ROOT_DIR/04_rlhf_fundamentals/human_feedback/preference_learning.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/human_feedback/reward_modeling.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/human_feedback/comparison_data.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/human_feedback/annotation_quality.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/human_feedback/inter_annotator_agreement.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/human_feedback/active_learning.md"

mkdir -p "$ROOT_DIR/04_rlhf_fundamentals/alignment_objectives"
touch "$ROOT_DIR/04_rlhf_fundamentals/alignment_objectives/helpfulness.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/alignment_objectives/harmlessness.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/alignment_objectives/honesty.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/alignment_objectives/constitutional_ai.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/alignment_objectives/value_alignment.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/alignment_objectives/safety_constraints.md"

mkdir -p "$ROOT_DIR/04_rlhf_fundamentals/rlhf_pipeline"
touch "$ROOT_DIR/04_rlhf_fundamentals/rlhf_pipeline/sft_stage.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/rlhf_pipeline/reward_model_training.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/rlhf_pipeline/rl_optimization.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/rlhf_pipeline/iterative_refinement.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/rlhf_pipeline/evaluation_feedback.md"

mkdir -p "$ROOT_DIR/04_rlhf_fundamentals/alternative_approaches"
touch "$ROOT_DIR/04_rlhf_fundamentals/alternative_approaches/dpo_direct_preference.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/alternative_approaches/constitutional_methods.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/alternative_approaches/self_supervised_alignment.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/alternative_approaches/debate_amplification.md"
touch "$ROOT_DIR/04_rlhf_fundamentals/alternative_approaches/recursive_reward_modeling.md"

# 05_model_compression
mkdir -p "$ROOT_DIR/05_model_compression/quantization"
touch "$ROOT_DIR/05_model_compression/quantization/post_training_quantization.md"
touch "$ROOT_DIR/05_model_compression/quantization/quantization_aware_training.md"
touch "$ROOT_DIR/05_model_compression/quantization/int8_quantization.md"
touch "$ROOT_DIR/05_model_compression/quantization/fp16_mixed_precision.md"
touch "$ROOT_DIR/05_model_compression/quantization/bfloat16_optimization.md"
touch "$ROOT_DIR/05_model_compression/quantization/dynamic_quantization.md"
touch "$ROOT_DIR/05_model_compression/quantization/extreme_quantization.md"

mkdir -p "$ROOT_DIR/05_model_compression/pruning"
touch "$ROOT_DIR/05_model_compression/pruning/magnitude_pruning.md"
touch "$ROOT_DIR/05_model_compression/pruning/structured_pruning.md"
touch "$ROOT_DIR/05_model_compression/pruning/unstructured_pruning.md"
touch "$ROOT_DIR/05_model_compression/pruning/gradual_pruning.md"
touch "$ROOT_DIR/05_model_compression/pruning/lottery_ticket.md"
touch "$ROOT_DIR/05_model_compression/pruning/neural_architecture_search.md"

mkdir -p "$ROOT_DIR/05_model_compression/knowledge_distillation"
touch "$ROOT_DIR/05_model_compression/knowledge_distillation/teacher_student.md"
touch "$ROOT_DIR/05_model_compression/knowledge_distillation/response_distillation.md"
touch "$ROOT_DIR/05_model_compression/knowledge_distillation/feature_distillation.md"
touch "$ROOT_DIR/05_model_compression/knowledge_distillation/attention_distillation.md"
touch "$ROOT_DIR/05_model_compression/knowledge_distillation/progressive_distillation.md"
touch "$ROOT_DIR/05_model_compression/knowledge_distillation/self_distillation.md"

mkdir -p "$ROOT_DIR/05_model_compression/efficient_architectures"
touch "$ROOT_DIR/05_model_compression/efficient_architectures/mobilenet_variants.md"
touch "$ROOT_DIR/05_model_compression/efficient_architectures/efficientnet_scaling.md"
touch "$ROOT_DIR/05_model_compression/efficient_architectures/depthwise_separable.md"
touch "$ROOT_DIR/05_model_compression/efficient_architectures/grouped_convolutions.md"
touch "$ROOT_DIR/05_model_compression/efficient_architectures/neural_ode.md"

mkdir -p "$ROOT_DIR/05_model_compression/acceleration_techniques"
touch "$ROOT_DIR/05_model_compression/acceleration_techniques/kernel_fusion.md"
touch "$ROOT_DIR/05_model_compression/acceleration_techniques/memory_optimization.md"
touch "$ROOT_DIR/05_model_compression/acceleration_techniques/computation_graph_optimization.md"
touch "$ROOT_DIR/05_model_compression/acceleration_techniques/operator_fusion.md"
touch "$ROOT_DIR/05_model_compression/acceleration_techniques/dynamic_batching.md"

# 06_hardware_foundations
mkdir -p "$ROOT_DIR/06_hardware_foundations/gpu_architecture"
touch "$ROOT_DIR/06_hardware_foundations/gpu_architecture/cuda_cores.md"
touch "$ROOT_DIR/06_hardware_foundations/gpu_architecture/tensor_cores.md"
touch "$ROOT_DIR/06_hardware_foundations/gpu_architecture/memory_hierarchy.md"
touch "$ROOT_DIR/06_hardware_foundations/gpu_architecture/warp_scheduling.md"
touch "$ROOT_DIR/06_hardware_foundations/gpu_architecture/occupancy_optimization.md"
touch "$ROOT_DIR/06_hardware_foundations/gpu_architecture/ampere_architecture.md"
touch "$ROOT_DIR/06_hardware_foundations/gpu_architecture/hopper_architecture.md"
touch "$ROOT_DIR/06_hardware_foundations/gpu_architecture/gpu_programming_model.md"

mkdir -p "$ROOT_DIR/06_hardware_foundations/memory_systems"
touch "$ROOT_DIR/06_hardware_foundations/memory_systems/memory_types.md"
touch "$ROOT_DIR/06_hardware_foundations/memory_systems/memory_bandwidth.md"
touch "$ROOT_DIR/06_hardware_foundations/memory_systems/cache_hierarchy.md"
touch "$ROOT_DIR/06_hardware_foundations/memory_systems/memory_coalescing.md"
touch "$ROOT_DIR/06_hardware_foundations/memory_systems/unified_memory.md"
touch "$ROOT_DIR/06_hardware_foundations/memory_systems/memory_optimization_strategies.md"

mkdir -p "$ROOT_DIR/06_hardware_foundations/interconnect_technologies"
touch "$ROOT_DIR/06_hardware_foundations/interconnect_technologies/nvlink_analysis.md"
touch "$ROOT_DIR/06_hardware_foundations/interconnect_technologies/nvswitch_fabric.md"
touch "$ROOT_DIR/06_hardware_foundations/interconnect_technologies/infiniband_networking.md"
touch "$ROOT_DIR/06_hardware_foundations/interconnect_technologies/ethernet_alternatives.md"
touch "$ROOT_DIR/06_hardware_foundations/interconnect_technologies/pcie_limitations.md"
touch "$ROOT_DIR/06_hardware_foundations/interconnect_technologies/network_topology.md"

mkdir -p "$ROOT_DIR/06_hardware_foundations/specialized_hardware"
touch "$ROOT_DIR/06_hardware_foundations/specialized_hardware/tpu_architecture.md"
touch "$ROOT_DIR/06_hardware_foundations/specialized_hardware/fpga_acceleration.md"
touch "$ROOT_DIR/06_hardware_foundations/specialized_hardware/asic_design.md"
touch "$ROOT_DIR/06_hardware_foundations/specialized_hardware/neuromorphic_chips.md"
touch "$ROOT_DIR/06_hardware_foundations/specialized_hardware/optical_computing.md"
touch "$ROOT_DIR/06_hardware_foundations/specialized_hardware/quantum_computing.md"

mkdir -p "$ROOT_DIR/06_hardware_foundations/performance_modeling"
touch "$ROOT_DIR/06_hardware_foundations/performance_modeling/roofline_model.md"
touch "$ROOT_DIR/06_hardware_foundations/performance_modeling/arithmetic_intensity.md"
touch "$ROOT_DIR/06_hardware_foundations/performance_modeling/memory_bound_compute_bound.md"
touch "$ROOT_DIR/06_hardware_foundations/performance_modeling/profiling_tools.md"
touch "$ROOT_DIR/06_hardware_foundations/performance_modeling/benchmark_methodologies.md"

# 07_mathematical_foundations
mkdir -p "$ROOT_DIR/07_mathematical_foundations/linear_algebra"
touch "$ROOT_DIR/07_mathematical_foundations/linear_algebra/matrix_operations.md"
touch "$ROOT_DIR/07_mathematical_foundations/linear_algebra/eigenvalues_eigenvectors.md"
touch "$ROOT_DIR/07_mathematical_foundations/linear_algebra/singular_value_decomposition.md"
touch "$ROOT_DIR/07_mathematical_foundations/linear_algebra/low_rank_approximation.md"
touch "$ROOT_DIR/07_mathematical_foundations/linear_algebra/tensor_operations.md"
touch "$ROOT_DIR/07_mathematical_foundations/linear_algebra/numerical_stability.md"

mkdir -p "$ROOT_DIR/07_mathematical_foundations/optimization_theory"
touch "$ROOT_DIR/07_mathematical_foundations/optimization_theory/gradient_descent.md"
touch "$ROOT_DIR/07_mathematical_foundations/optimization_theory/stochastic_optimization.md"
touch "$ROOT_DIR/07_mathematical_foundations/optimization_theory/adam_optimizer.md"
touch "$ROOT_DIR/07_mathematical_foundations/optimization_theory/learning_rate_scheduling.md"
touch "$ROOT_DIR/07_mathematical_foundations/optimization_theory/regularization.md"
touch "$ROOT_DIR/07_mathematical_foundations/optimization_theory/constrained_optimization.md"
touch "$ROOT_DIR/07_mathematical_foundations/optimization_theory/convex_optimization.md"

mkdir -p "$ROOT_DIR/07_mathematical_foundations/probability_statistics"
touch "$ROOT_DIR/07_mathematical_foundations/probability_statistics/probability_distributions.md"
touch "$ROOT_DIR/07_mathematical_foundations/probability_statistics/bayesian_inference.md"
touch "$ROOT_DIR/07_mathematical_foundations/probability_statistics/maximum_likelihood.md"
touch "$ROOT_DIR/07_mathematical_foundations/probability_statistics/information_theory.md"
touch "$ROOT_DIR/07_mathematical_foundations/probability_statistics/entropy_cross_entropy.md"
touch "$ROOT_DIR/07_mathematical_foundations/probability_statistics/statistical_significance.md"

mkdir -p "$ROOT_DIR/07_mathematical_foundations/numerical_methods"
touch "$ROOT_DIR/07_mathematical_foundations/numerical_methods/floating_point_arithmetic.md"
touch "$ROOT_DIR/07_mathematical_foundations/numerical_methods/numerical_precision.md"
touch "$ROOT_DIR/07_mathematical_foundations/numerical_methods/iterative_methods.md"
touch "$ROOT_DIR/07_mathematical_foundations/numerical_methods/approximation_algorithms.md"
touch "$ROOT_DIR/07_mathematical_foundations/numerical_methods/error_analysis.md"

# 08_software_foundations
mkdir -p "$ROOT_DIR/08_software_foundations/deep_learning_frameworks"
touch "$ROOT_DIR/08_software_foundations/deep_learning_frameworks/pytorch_fundamentals.md"
touch "$ROOT_DIR/08_software_foundations/deep_learning_frameworks/tensorflow_overview.md"
touch "$ROOT_DIR/08_software_foundations/deep_learning_frameworks/jax_functional_programming.md"
touch "$ROOT_DIR/08_software_foundations/deep_learning_frameworks/framework_comparison.md"
touch "$ROOT_DIR/08_software_foundations/deep_learning_frameworks/automatic_differentiation.md"
touch "$ROOT_DIR/08_software_foundations/deep_learning_frameworks/computational_graphs.md"
touch "$ROOT_DIR/08_software_foundations/deep_learning_frameworks/dynamic_static_graphs.md"

mkdir -p "$ROOT_DIR/08_software_foundations/parallel_programming"
touch "$ROOT_DIR/08_software_foundations/parallel_programming/cuda_programming.md"
touch "$ROOT_DIR/08_software_foundations/parallel_programming/opencl_overview.md"
touch "$ROOT_DIR/08_software_foundations/parallel_programming/openmp_parallelization.md"
touch "$ROOT_DIR/08_software_foundations/parallel_programming/mpi_message_passing.md"
touch "$ROOT_DIR/08_software_foundations/parallel_programming/threading_models.md"
touch "$ROOT_DIR/08_software_foundations/parallel_programming/async_programming.md"

mkdir -p "$ROOT_DIR/08_software_foundations/system_programming"
touch "$ROOT_DIR/08_software_foundations/system_programming/memory_management.md"
touch "$ROOT_DIR/08_software_foundations/system_programming/process_thread_management.md"
touch "$ROOT_DIR/08_software_foundations/system_programming/io_optimization.md"
touch "$ROOT_DIR/08_software_foundations/system_programming/network_programming.md"
touch "$ROOT_DIR/08_software_foundations/system_programming/file_system_optimization.md"
touch "$ROOT_DIR/08_software_foundations/system_programming/kernel_optimization.md"

mkdir -p "$ROOT_DIR/08_software_foundations/software_engineering"
touch "$ROOT_DIR/08_software_foundations/software_engineering/version_control.md"
touch "$ROOT_DIR/08_software_foundations/software_engineering/testing_strategies.md"
touch "$ROOT_DIR/08_software_foundations/software_engineering/continuous_integration.md"
touch "$ROOT_DIR/08_software_foundations/software_engineering/code_quality.md"
touch "$ROOT_DIR/08_software_foundations/software_engineering/documentation.md"
touch "$ROOT_DIR/08_software_foundations/software_engineering/project_management.md"

# 09_hands_on_labs
mkdir -p "$ROOT_DIR/09_hands_on_labs/transformer_implementation/attention_from_scratch"
mkdir -p "$ROOT_DIR/09_hands_on_labs/transformer_implementation/transformer_block"
mkdir -p "$ROOT_DIR/09_hands_on_labs/transformer_implementation/positional_encoding_experiments"
mkdir -p "$ROOT_DIR/09_hands_on_labs/transformer_implementation/scaling_experiments"

mkdir -p "$ROOT_DIR/09_hands_on_labs/distributed_computing/mpi_hello_world"
mkdir -p "$ROOT_DIR/09_hands_on_labs/distributed_computing/cuda_matrix_multiplication"
mkdir -p "$ROOT_DIR/09_hands_on_labs/distributed_computing/nccl_communication"
mkdir -p "$ROOT_DIR/09_hands_on_labs/distributed_computing/pytorch_distributed"

mkdir -p "$ROOT_DIR/09_hands_on_labs/optimization_experiments/gradient_descent_variants"
mkdir -p "$ROOT_DIR/09_hands_on_labs/optimization_experiments/learning_rate_schedules"
mkdir -p "$ROOT_DIR/09_hands_on_labs/optimization_experiments/regularization_effects"
mkdir -p "$ROOT_DIR/09_hands_on_labs/optimization_experiments/batch_size_analysis"

mkdir -p "$ROOT_DIR/09_hands_on_labs/quantization_pruning/post_training_quantization_demo"
mkdir -p "$ROOT_DIR/09_hands_on_labs/quantization_pruning/magnitude_pruning_experiment"
mkdir -p "$ROOT_DIR/09_hands_on_labs/quantization_pruning/knowledge_distillation_demo"
mkdir -p "$ROOT_DIR/09_hands_on_labs/quantization_pruning/compression_comparison"

mkdir -p "$ROOT_DIR/09_hands_on_labs/performance_analysis/profiling_experiments"
mkdir -p "$ROOT_DIR/09_hands_on_labs/performance_analysis/memory_usage_analysis"
mkdir -p "$ROOT_DIR/09_hands_on_labs/performance_analysis/gpu_utilization_study"
mkdir -p "$ROOT_DIR/09_hands_on_labs/performance_analysis/scaling_law_verification"

# resources
mkdir -p "$ROOT_DIR/resources/papers/foundational_papers"
mkdir -p "$ROOT_DIR/resources/papers/architecture_papers"
mkdir -p "$ROOT_DIR/resources/papers/optimization_papers"
mkdir -p "$ROOT_DIR/resources/papers/system_papers"
mkdir -p "$ROOT_DIR/resources/books"
mkdir -p "$ROOT_DIR/resources/courses"
mkdir -p "$ROOT_DIR/resources/tools"
touch "$ROOT_DIR/resources/useful_links.md"

echo "目录结构 '$ROOT_DIR' 创建成功！"
